version: '3'

services: #Servicio postgres
  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      #Servicio pagina principal
  nodejs_main:
    image: node:20.10-alpine3.17
    working_dir: /app
    volumes:
      - ../../app:/app
    command: ["npm","start"] # TODO:Ajusta según la forma en que inicies tu aplicación Node.js
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      #Servicio microservicio tareas
  nodejs_task:
    image: node:20.10-alpine3.17  # Utilizando Node.js versión 14 como ejemplo
    working_dir: /app
    volumes:
      - ./tareas:/app
    command: ["npm", "start"]  # TODO:Ajusta según la forma en que inicies tu aplicación Node.js
    ports:
      - "3001:3000"  # TODO:Ajusta el puerto según la configuración de tu aplicación
    depends_on:
      - postgres
        #Servicio microservicio 
  nodejs_users:
    image: node:20.10-alpine3.17  # Utilizando Node.js versión 14 como ejemplo
    working_dir: /app
    volumes:
      - ./usuarios:/app
    command: ["npm", "start"]  # TODO:Ajusta según la forma en que inicies tu aplicación Node.js
    ports:
      - "3002:3000"  # TODO:Ajusta el puerto según la configuración de tu aplicación
    depends_on:
      - postgres
volumes:
  postgres_data:
